  
name: workflow name

on: 
  release:

jobs:
  build:
    runs-on: [self-hosted, linux, ARM32]
    steps:
    - uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
