name: fast farword merge
on: pull_request

jobs:
  build-and-test:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: check1
        id: filepath
        run: |
           echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: show commit message
        run : echo $commitmsg
      - name: step1
        if: contains( env.commitmsg , 'try' )
        run: echo hello
      
