name: fast farword merge
on: pull_request

jobs:
  build-and-test:
    if: contains( $(git log --format=%B -n 1 github.event.after ), 'try' )
    runs-on: ubuntu-latest
    steps:
      - name: check1
        id: filepath
        run: |
           echo ::set-output name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: show commit message
        run : echo ${{ steps.filepath.outputs.commitmsg }}
      
