name: test ignore path 
on: 
  push:
    paths:
      - '**'
      - '!dev2.txt'
      - '!dev.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Notified on success
        if: success()
        run: echo notify me on build success

