name: docker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - name: check1
      id: filepath
      run: |
          echo ::set-output name=commitpath::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
    - name: echo
      run: |
          echo ${{ steps.filepath.outputs.commitpath }}
    - name: publish
      if: Contains(steps.filepath.outputs.commitpath, 'dev.txt') || Contains(steps.filepath.outputs.commitpath, 'dev2.txt')
      run: echo 'include path'
   
   
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
   

    
